services:
  db:
    image: postgres:17.9
    container_name: password-manager-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d password_manager"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: password-manager-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data: